// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	context "context"

	input "github.com/jhmorais/device-manager/internal/usecases/ports/input"

	mock "github.com/stretchr/testify/mock"

	output "github.com/jhmorais/device-manager/internal/usecases/ports/output"
)

// CreateDeviceUseCase is an autogenerated mock type for the CreateDeviceUseCase type
type CreateDeviceUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, createDevice
func (_m *CreateDeviceUseCase) Execute(ctx context.Context, createDevice *input.CreateDeviceInput) (*output.CreateDeviceOutput, error) {
	ret := _m.Called(ctx, createDevice)

	var r0 *output.CreateDeviceOutput
	if rf, ok := ret.Get(0).(func(context.Context, *input.CreateDeviceInput) *output.CreateDeviceOutput); ok {
		r0 = rf(ctx, createDevice)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*output.CreateDeviceOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *input.CreateDeviceInput) error); ok {
		r1 = rf(ctx, createDevice)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCreateDeviceUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewCreateDeviceUseCase creates a new instance of CreateDeviceUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCreateDeviceUseCase(t mockConstructorTestingTNewCreateDeviceUseCase) *CreateDeviceUseCase {
	mock := &CreateDeviceUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
