// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	output "github.com/jhmorais/device-manager/internal/usecases/ports/output"
)

// DeleteDeviceUseCase is an autogenerated mock type for the DeleteDeviceUseCase type
type DeleteDeviceUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, deviceID
func (_m *DeleteDeviceUseCase) Execute(ctx context.Context, deviceID string) (*output.DeleteDeviceOutput, error) {
	ret := _m.Called(ctx, deviceID)

	var r0 *output.DeleteDeviceOutput
	if rf, ok := ret.Get(0).(func(context.Context, string) *output.DeleteDeviceOutput); ok {
		r0 = rf(ctx, deviceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*output.DeleteDeviceOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, deviceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewDeleteDeviceUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeleteDeviceUseCase creates a new instance of DeleteDeviceUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeleteDeviceUseCase(t mockConstructorTestingTNewDeleteDeviceUseCase) *DeleteDeviceUseCase {
	mock := &DeleteDeviceUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
